[book]
authors = ["许杰友 Jieyou Xu (Joe)"]
language = "en"
multilingual = false
src = "src"
title = "jieyouxu vs compiletest"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/jieyouxu/jieyouxu-vs-compiletest"
